name: spending_tracker
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  intl: ^0.18.1
  flutter_svg: ^2.0.17
  fl_chart: ^0.63.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  provider: ^6.1.1
  file_picker: ^8.1.6
  share_plus: ^7.2.1
  
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  drift_dev: ^2.14.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/imgs/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#708E2B" # Kiwi green color
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_mask: true
